//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinopoiskLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<title>(?<RussianTitle>[^<]*)</title>")]
        public string RussianTitlePattern {
            get {
                return ((string)(this["RussianTitlePattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<span itemprop=\"alternativeHeadline\">(?<OriginalTitle>[^<]*)</span>")]
        public string OriginalTitlePattern {
            get {
                return ((string)(this["OriginalTitlePattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<div class=\"brand_words\" itemprop=\"description\">(?<Description>[^/]*)</div>")]
        public string DescriptionPattern {
            get {
                return ((string)(this["DescriptionPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<a href=\"/film/[0-9]+/dates/\" title=\"\">(?<ReleaseDate>[^/]*)</a>")]
        public string ReleaseDatePattern {
            get {
                return ((string)(this["ReleaseDatePattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<a href=\"/level/8/view/prem/year/[0-9]+/#[0-9]+\">(?<ReleaseDate>[^/]*)</a>")]
        public string ReleaseDateRusPattern {
            get {
                return ((string)(this["ReleaseDateRusPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<a href=\"/lists/m_act%5Bgenre%5D/[0-9]+/\">(?<Genre>[а-я]+)</a>")]
        public string GenrePattern {
            get {
                return ((string)(this["GenrePattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.kinopoisk.ru/index.php?first=yes&kp_query={0}")]
        public string KinopoiskSearchUrlPattern {
            get {
                return ((string)(this["KinopoiskSearchUrlPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://st.kp.yandex.net/images/poster/sm_(?<PosterId>[0-9]+).jpg")]
        public string PosterUrlPattern {
            get {
                return ((string)(this["PosterUrlPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<a href=\\\"/name/(?<PersonId>[0-9]+)/\\\">(?<RussianName>[^<]+)</a> <span class=\\\"gr" +
            "ay\\\">(?<EnglishName>[^<]+)</span></div>[^<]+<div class=\\\"role\\\">(... )?(?<Role>[" +
            "^<]+)?")]
        public string PersonPattern {
            get {
                return ((string)(this["PersonPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<div style=\"padding-left: 20px; border-bottom: 2px solid #f60; font-size: 16px\">(" +
            "?<Department>[^<]+)</div>")]
        public string DepartmentPattern {
            get {
                return ((string)(this["DepartmentPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tr-by.kinopoisk.ru/images/actor/{0}.jpg")]
        public string PhotoUrlPattern {
            get {
                return ((string)(this["PhotoUrlPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.kinopoisk.ru/film/{0}")]
        public string KinopoiskFilmDetailUrlPattern {
            get {
                return ((string)(this["KinopoiskFilmDetailUrlPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.kinopoisk.ru/film/{0}/cast/")]
        public string KinopoiskFilmActorsUrlPattern {
            get {
                return ((string)(this["KinopoiskFilmActorsUrlPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.kinopoisk.ru/film/{0}/posters/")]
        public string KinopoiskFilmPostersUrlPattern {
            get {
                return ((string)(this["KinopoiskFilmPostersUrlPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.kinopoisk.ru/film/{0}/like/")]
        public string KinopoiskFilmRelatedUrlPattern {
            get {
                return ((string)(this["KinopoiskFilmRelatedUrlPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<a style=\"font-size: 13px; font-weight: bold\" href=\"/film/(?<KinopoiskId>[0-9]+)/" +
            "\" class=\"all\">")]
        public string RelatedMoviesPattern {
            get {
                return ((string)(this["RelatedMoviesPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td class=\"time\" id=\"runtime\">(?<Duration>[0-9]+) мин.")]
        public string DurationPattern {
            get {
                return ((string)(this["DurationPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ageLimit age(?<AgeLimit>[0-9]+)")]
        public string AgeLimitPattern {
            get {
                return ((string)(this["AgeLimitPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://st.kp.yandex.net/images/mpaa/(?<Rating>[^\\.]+).gif")]
        public string MPAAPattern {
            get {
                return ((string)(this["MPAAPattern"]));
            }
        }
    }
}
